---
name: py39
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyter
  - jupyterlab
  - matplotlib
  - numpy
  - pandas
  - pip
  - pre_commit
  - python=3.9
  - seaborn
  - scipy
  - statsmodels
  - tox
